### PR TITLE
Initial runner

### PR DESCRIPTION
**Pull request by sam-github**
Changes to support strong-runner

connect to strongloop-internal/scrum-nodeops#307

### CODE REVIEW

**Comment by sam-github** [comment]
@kraman, PTAL

**Comment by kraman** [comment]
LGTM. Afaik the status messages are redundant because mesh-models/pm makes a status request to get that info. but no hard in having it as well.

**Comment by sam-github** [comment]
re: status, yes, pm queries at start, but I also think it reacts to updates.

The unit tests wait for status updates, its safer to wait, because otherwise you have to poll, because you might be sending your status request before the child has started...

Anyhow, the runner tests wait for status, and the versions that were running with cluster size of `0` were failing due to lack of status, that's why I added, not for strong-pm, directly.

**Comment by sam-github** [comment]
test please

**Comment by sam-github** [comment]
test please

**Comment by rmg** [comment]
@slnode test please

**Pull request merged**
