### PR TITLE
express probe added to adapter

### PR DESCRIPTION
**Pull request by mattcolegate**
Probe for Express now added to appmetrics, adding to the adapter

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by tobespc** [comment]
LGTM

**Pull request merged**
