### PR TITLE
Report debuggerVersion in status messages

### PR DESCRIPTION
**Pull request by bajtos**
Connect to strongloop-internal/scrum-loopback#261

/to @kraman please review
/cc @sam-github

### CODE REVIEW

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
The CI build is failing on this (seemingly unrelated?) test:

```
        # Subtest: scaleDown
Mon, 14 Sep 2015 14:23:18 GMT strong-control-channel:process:24381 dst 24386 request {"cmd":"set-size","size":1}
Mon, 14 Sep 2015 14:23:18 GMT strong-control-channel:process:24386 protocol request #1 {"cmd":"set-size","size":1}
Mon, 14 Sep 2015 14:23:18 GMT strong-supervisor:runctl request {"cmd":"set-size","size":1}
Mon, 14 Sep 2015 14:23:18 GMT strong-cluster-control:master set size to 1 from 2
Mon, 14 Sep 2015 14:23:18 GMT strong-control-channel:process:24386 protocol response #1 {}
    pid:24386 worker:0 INFO supervisor size set to 1
Mon, 14 Sep 2015 14:23:18 GMT strong-cluster-control:master _resize: w? undefined
Mon, 14 Sep 2015 14:23:18 GMT strong-cluster-control:master resize to 1 from 2 resizing? false
Mon, 14 Sep 2015 14:23:18 GMT strong-cluster-control:master considering worker 1 for stop connected? true
Mon, 14 Sep 2015 14:23:18 GMT strong-cluster-control:master shutdown 1 already? false
        not ok 1 - test unfinished: scaleDown
          ---
          at:
            file: test/test-ipcctl-notifications.js
            line: 109
            column: 1
          source: |
            test('scaleDown', function(t) {
          ...
        Bail out! # test unfinished: scaleDown
Bail out! # test unfinished: scaleDown
/mnt/jenkins/workspace/strong-supervisor.pr/292db481/node_modules/tap/lib/test.js:870
    throw er
    ^

Error: test count exceeds plan
    at EventEmitter.<anonymous> (/mnt/jenkins/workspace/strong-supervisor.pr/292db481/test/test-ipcctl-notifications.js:85:7)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at onRequest (/mnt/jenkins/workspace/strong-supervisor.pr/292db481/test/test-ipcctl-notifications.js:35:6)
    at Protocol.onNotification (/mnt/jenkins/workspace/strong-supervisor.pr/292db481/node_modules/strong-control-channel/lib/process.js:10:5)
    at Immediate.immediate._onImmediate (timers.js:423:18)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

Any idea what may be wrong here?

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
@slnode  test please

**Comment by kraman** [comment]
@slnode test please

**Comment by bajtos** [comment]
@kraman ha! your patch fixed the problem. I'll squash the commits into a single on, so that this PR can be landed once you give it LGTM.

**Comment by bajtos** [comment]
@kraman LGTY now?

**Comment by kraman** [comment]
@slnode test please

**Comment by kraman** [comment]
:+1:

**Pull request merged**
