### PR TITLE
package: remove strong-debugger

### PR DESCRIPTION
**Pull request by sam-github**
It isn't used, but takes time to build, and fails to build on some
platforms.

### CODE REVIEW

**Comment by sam-github** [comment]
cc: @kraman @rmg

**Comment by rmg** [comment]
@sam-github is this meant as a conversation starter? The debugger related tests are, unsurprisingly, failing..

**Comment by sam-github** [comment]
@rmg yes, sorry, conversation starter.

@bajtos do you object?

**Comment by bajtos** [comment]
> It isn't used, but takes time to build, and fails to build on some platforms.
> do you object?

I believe we will be resuming the work on the debugger in Arc/API Connect soon, I have a story in my backlog to hand over this work to you and your team, @sam-github.

Now if you think it's easier to remove strong-debugger now and then add it back again when the work is resumed, then I don't mind.

/cc @chandadharap

**Comment by bajtos** [comment]
Ah, based on Sam's https://github.com/strongloop-internal/scrum-loopback/issues/835#issuecomment-214556766, I don't have any objections.

**Comment by sam-github** [comment]
@slnode test please

**Pull request merged**
