### PR TITLE
honour path in --control ws:url/path

### PR DESCRIPTION
**Pull request by rmg**
Depends on strongloop/strong-control-channel#24 for updated mock
server implementation.

@sam-github or @piscisaureus PTAL

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by sam-github** [comment]
https://github.com/strongloop/strong-url-defaults#url--defaultsurl-defaults-overrides

> Its not possible to distinguish with url.parse() whether a path was supplied, so it can't be "defaulted".

Are you sure this works? I don't think its possible to tell if path has a value or not, so it wasn't supported in the defaults, just the overrides.

If it works, I'm ok with it, though I don't understand why pm and central wouldn't want to have a fixed path for supervisor's websockets. Why would we need to  support configurability of this?

**Comment by rmg** [comment]
@sam-github the problem is PM, central, and supervisor all have to have the path hard coded to the same value... in other words, changing is requires 3 PRs and 3 major version bumps.

Seems to me that the server should set and provide the URL and the client should get and use it.

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
re: url defaults - I've pushed a fixup that removes path entirely from the defaults/override logic.

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by sam-github** [comment]
Why should the path be changed? Location of the api is part of the api contract.

Anyhow, the current behaviour is intended to work like

```
slc ctl --control http://example.com:9999 info
sl-run --control http://TOKEN@example.com:9999
```

We don't force people to type in '/api' as the path in the other `--control` options, so why would we for supervisor?

Or so went my thinking. If that flexibility in under-specifying the control URL is turning into a PITA, then I've no objections, just so you can see what the thinking was.

LGTM-if-you-are-sure-its-a-good-idea

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@sam-github I think we will find this path change useful when we need to start routing requests by path in central.

**Comment by sam-github** [comment]
So, can you justify this change some more?

It broke executor, which didn't know that it had to know about the path that supervisor should use. And why should it know, its none of its business which path supervisor and central want to use, is it?

I suspect your model is that the URL somehow comes from central, thus, it can provide a full URL, and so supervisor needs no dependence on what the URL is, it can be anything. If so, that would be reasonable, except its not how it works.

central doesn't construct the URL that the supervisor should use. What happens is that executor knows the IP and port of central, from its perspective (central could have multiple IPs, or NAT between it and the executor). Executor then constructs the URL, and it knows it wants to connect to `executor-control`. And now, it uses the `http://token@ip:port` URL it gets to construct the supervisor control URL, too... so it knows MORE  than the supervisor does about the supervisor's control path/API endpoint, which seems weird: https://github.com/strongloop/strong-executor/pull/6

We don't specify `slc ctl -C http://localhost:9701/api` (note the api endpoint) or provide the endpoint in sl-deploy, or arc, or sl-executor, so why should we have to specify the api endpoint in `sl-run -C http://localhost:8701/supervisor-control`?

**Comment by rmg** [comment]
Re-reading my comments, it looks like my intention was merely to _allow_ the path to be given, not require it, but strong-url-defaults wouldn't let me.

**Pull request merged**
