### PR TITLE
Use modern-syslog, not our fork of node-syslog

### PR DESCRIPTION
**Pull request by sam-github**
I did a quick test, the tests pass, and I did a `slc run --syslog --cluster=1` of the express example app, and the output was indeed syslogged.

connected to strongloop-internal/scrum-nodeops#893

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
Build failures were caused by upstream change and are fixed by #156.

**Comment by rmg** [comment]
@sam-github #156 has been merged, can you rebase so we can see if this PR passes CI?

**Comment by rmg** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by rmg** [comment]
LGTM, :shipit:

**Pull request merged**
