### PR TITLE
Fix eslint errors

### PR DESCRIPTION
**Pull request by kjdelisle**
connected to https://github.com/strongloop-internal/scrum-nodeops/issues/1596

### CODE REVIEW

**Comment by kjdelisle** [comment]
PTAL @sam-github

**Comment by sam-github** [comment]
Commit body should be either a bullet list, or a properly formed paragraph (with sentence-ending periods).

**Comment by sam-github** [comment]
I think I would use commit subject of 'Add 'use strict' to all files', fix eslint errors is kindof vague. And the only thing that wasn't the insert of use strict was the package... and that only applies in strict mode, so it is a use strict thing.

**Comment by kjdelisle** [comment]
@sam-github I might just split the commit into two commits; I originally used a vague wording because there is a change to one file that isn't related to the 'use strict' change

**Comment by kjdelisle** [comment]
@sam-github All good now?

**Comment by sam-github** [comment]
@kjdelisle did you mean to merge those two commits together?

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
@sam-github PTAL

**Comment by sam-github** [comment]
LGTM

**Pull request merged**
