### PR TITLE
disable node core timer wrapping for tracing navigation clarity

### PR DESCRIPTION
**Pull request by Setogit**
connect to strongloop-internal/scrum-nodeops#740

### CODE REVIEW

**Comment by altsang** [comment]
LGTM :+1:

**Comment by Setogit** [comment]
@sam-github : will you review?

**Comment by sam-github** [comment]
LGTM, though I'm a bit confused: if the app calls setInterval, shouldn't you see it? This isn't like the strong-agent calls, which we hide because they are activity unrelated (directly) to the app.

@altsang @ijroth

**Comment by Setogit** [comment]
Right, the nature of this change is different from blacklisting strong-agent.  Blacking listing modules disable instrumentation of functions in the modules.  Wrapping timer functions such as setInterval as well as DB, HTTP transactions determines the list of Trace Sequences that the user sees as entry points to drill down to waterfalls and flame graphs which is built from the tracing data collected by the function instrumentation.

The legacy Concurix navigation model is the following; it leaves many possible navigation entry points and paths open to the user.  The user can easily scan across the transaction boundary to browse all waterfalls, flamegraphs from anywhere.  The legacy navigation model provides flexibility, but confusing if you don't know exactly what you are doing and when you cross the transaction boundary.  We decided to make StrongLoop tracing Navigation Model to make the navigation flow very focused on HTTP and DB transactions.  No ways to cross the transaction boundary once the user picks one; he needs to go back to the Trace Sequences list and re-pick another transaction.  At StrongLoop, we value the clarity over the flexibility.

This PR brings Tracing one more step closer to the StrongLoop tracing navigation model.

**Comment by sam-github** [comment]
@slnode test please

**Comment by rmg** [comment]
cherry-picked to 2.x branch, released in strong-supervisor@2.0.2

**Pull request merged**
