### PR TITLE
Backport non-breaking changes from 5.x

### LINKED ISSUE #203: JSON.stringify crash
I would like to point you to
https://github.com/strongloop/strong-pm/issues/307
since it may actually concern this subproject.

### PR DESCRIPTION
**Pull request by rmg**
I'd like to publish a maintenance release of the 3.x line. This is all of the non-breaking changes that have been merged to master + #201.

@sam-github in order to resolve #203, I'm considering back-porting 1a36fb4 (the one commit from #199 that was skipped), but I'm not sure if we should consider it a breaking change or not. Technically, it is removing a feature and therefore breaking.. but I don't know if it was ever actually used or documented, which would make it a non-semver-major change. Thoughts?

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by sam-github** [comment]
LGTM

Also, the removing of agent:trace (1a36fb4) seems fine to me. strong-pm used the feature, but if its test aren't broken (and the green for this PR on ci indicates it isn't) then it should be OK.

**Comment by rmg** [comment]
@sam-github I hadn't included the agent-trace removal in the first batch, but I've just added it. We'll see shortly whether it breaks strong-pm or not.

**Comment by rmg** [comment]
It passes, but as far as I can tell the only test in strong-pm for `agent:trace` is not only [skipped](https://github.com/strongloop/strong-pm/blob/master/test/test-trace-data.js#L94-L96), but even if it was run it is [tested with mocks](https://github.com/strongloop/strong-pm/blob/master/test/test-trace-data.js#L128-L136) anyway :-(

From a code walk through strong-pm, strong-mesh-models, and strong-arc, though, I agree with your original assessment that it is completely unused.

@sam-github can I get one more LGTM to `ACK` this before I merge? Just want to make sure I'm reading you correctly.

**Comment by sam-github** [comment]
LGTM

**Pull request merged**
