### PR TITLE
Cleanup tests

### PR DESCRIPTION
**Pull request by rmg**
The first commit fixes a bug I found while seeing what the tests do when you don't have a license. The third commit actually skips the tests that require a license if there isn't one defined.

Everything else is just cleanup that happened around those. I particularly like the last commit.

### CODE REVIEW

**Comment by rmg** [comment]
Turns out the coverage breaks a lot of things.. not sure how it managed to run for me locally the first few times, but it seems to be failing constantly for me now.

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
Much better. The full `npm test` runs in about 2 minutes for me and for CI, on a clean checkout.

@sam-github PTAL

**Comment by sam-github** [comment]
LGTM, except for the error message format.

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Pull request merged**
