### PR TITLE
tracer: fix require of app's package.json

### PR DESCRIPTION
**Pull request by sam-github**

### CODE REVIEW

**Comment by rmg** [comment]
Can't it get the app name from the agent? It's using the agent to get `lrtime` just a few lines down from where it calls `getAppName()`.

**Comment by Setogit** [comment]
I'm new to multi-app.  With that said, LGTM.

**Comment by sam-github** [comment]
@rmg because the agent initis `internal.lrtime` in the constructor (on require), but doesn't init the appName until it's configured... and tracer needs to start before the agent is configured.

This is very, very, ugly. tracer should be injecting the app name later, when the trace object is emitted, or else be calling config. Lets rework sometime, but for now, this will unblock Sean & Co.

**Comment by rmg** [comment]
https://github.com/strongloop/strongops/blob/a073d09b78b8d4f656ee59cffadb42201b2322f1/agent/lib/agent.js#L43

**Comment by sam-github** [comment]
We should merge this to unblock Sean

This code is broken, by calling `agent()` we are preventing the tracer from instrumenting anything that `agent()/require('strong-agent')` requires.

We need to fix, but not right this half hour.

**Comment by rmg** [comment]
LGTM, :shipit:

**Pull request merged**
